add tools (mail, script, todo)
T5uku5hi/workshop-manual pull request #1
Opened 2018-07-16 02:36 UTC by T5uku5hi

2018-07-16 04:39 UTC, cho0o0 requested changes

2018-07-16 04:39 UTC, cho0o0 commented on tools/todo-list.md
> +- [ ] プロジェクターチェック
変換コードに関する記述を加えた方が良いです？

2018-07-16 04:39 UTC, cho0o0 commented on tools/todo-list.md
> +- [ ] 受付場所の設置
受付のやり方についての説明がなかったようですね。加えた方がいいです？

2018-07-16 04:39 UTC, cho0o0 commented on tools/todo-list.md
> +- [ ] タイムキーパー
終了後のやることに関する記述が少なさそうですね。
- 忘れ物関係
- 感謝メール/ツイート
- 資料・スライドの共有

についての説明を加えた方がいいと思います。

2018-07-16 16:14 UTC, T5uku5hi commented on tools/todo-list.md
> +- [ ] プロジェクターチェック
記述を加えてみました！

2018-07-16 16:14 UTC, T5uku5hi commented on tools/todo-list.md
> +- [ ] 受付場所の設置
READMEの方に加えました！

2018-07-16 16:15 UTC, T5uku5hi commented on tools/todo-list.md
> +- [ ] タイムキーパー
ご指摘ありがとうございます✨
README, todoの両方に加えました！

2018-07-16 16:37 UTC, T5uku5hi commented
@cho0o0 修正しました！
ご確認よろしくお願いしますm(_ _)m

2018-07-17 06:14 UTC, cho0o0 approved these changes
レビューOKです。

2018-07-17 07:57 UTC, T5uku5hi commented
ありがとうございます！

2018-07-17 07:57 UTC, merged